// ── Application ───────────────────────────────────────────────────────────────
export { Application } from './application/Application.ts'

// ── Macroable ────────────────────────────────────────────────────────────────
export { Macroable, applyMacros } from './macroable/Macroable.ts'
export type { MacroableStatic, MacroableInstance } from './macroable/Macroable.ts'

// ── Contracts (interfaces + base classes) ────────────────────────────────────
export type { Container, Bindable, Resolvable, Constructor, ContextualBindingBuilder } from './contracts/Container.ts'
export type { Config } from './contracts/Config.ts'
export type { Middleware, NextFunction } from './contracts/Middleware.ts'
export type { MantiqRequest } from './contracts/Request.ts'
export type { MantiqResponseBuilder, CookieOptions } from './contracts/Response.ts'
export type { Router, RouterRoute, RouteAction, RouteGroupOptions, RouteMatch, RouteDefinition, HttpMethod } from './contracts/Router.ts'
export type { ExceptionHandler } from './contracts/ExceptionHandler.ts'
export type { DriverManager } from './contracts/DriverManager.ts'
export type { Encrypter } from './contracts/Encrypter.ts'
export type { Hasher } from './contracts/Hasher.ts'
export type { CacheStore } from './contracts/Cache.ts'
export type { SessionHandler, SessionConfig } from './contracts/Session.ts'
export type { EventDispatcher, EventHandler } from './contracts/EventDispatcher.ts'
export { ServiceProvider } from './contracts/ServiceProvider.ts'
export { Event, Listener } from './contracts/EventDispatcher.ts'
export type { WebSocketHandler, WebSocketContext } from './websocket/WebSocketContext.ts'

// ── Errors ────────────────────────────────────────────────────────────────────
export { MantiqError } from './errors/MantiqError.ts'
export { HttpError } from './errors/HttpError.ts'
export { NotFoundError } from './errors/NotFoundError.ts'
export { UnauthorizedError } from './errors/UnauthorizedError.ts'
export { ForbiddenError } from './errors/ForbiddenError.ts'
export { ValidationError } from './errors/ValidationError.ts'
export { TooManyRequestsError } from './errors/TooManyRequestsError.ts'
export { ContainerResolutionError } from './errors/ContainerResolutionError.ts'
export { ConfigKeyNotFoundError } from './errors/ConfigKeyNotFoundError.ts'
export { TokenMismatchError } from './errors/TokenMismatchError.ts'
export { EncryptionError, DecryptionError, MissingAppKeyError } from './encryption/errors.ts'

// ── Implementations ───────────────────────────────────────────────────────────
export { ContainerImpl } from './container/Container.ts'
export { ConfigRepository } from './config/ConfigRepository.ts'
export { MantiqRequest as MantiqRequestImpl } from './http/Request.ts'
export { MantiqResponse, ResponseBuilder } from './http/Response.ts'
export { serializeCookie, parseCookies } from './http/Cookie.ts'
export { UploadedFile } from './http/UploadedFile.ts'
export { HttpKernel } from './http/Kernel.ts'
export { RouterImpl } from './routing/Router.ts'
export { Route } from './routing/Route.ts'
export { RouteMatched } from './routing/events.ts'
export { Pipeline } from './middleware/Pipeline.ts'
export { CorsMiddleware } from './middleware/Cors.ts'
export { TrimStringsMiddleware } from './middleware/TrimStrings.ts'
export { StartSession } from './middleware/StartSession.ts'
export { EncryptCookies } from './middleware/EncryptCookies.ts'
export { VerifyCsrfToken } from './middleware/VerifyCsrfToken.ts'
export { RateLimiter, MemoryStore } from './rateLimit/RateLimiter.ts'
export type { RateLimitConfig, RateLimitStore, LimiterResolver } from './rateLimit/RateLimiter.ts'
export { ThrottleRequests } from './rateLimit/ThrottleRequests.ts'
export { WebSocketKernel } from './websocket/WebSocketKernel.ts'
export { DefaultExceptionHandler } from './exceptions/Handler.ts'
export { CoreServiceProvider } from './providers/CoreServiceProvider.ts'

// ── Encryption ────────────────────────────────────────────────────────────────
export { AesEncrypter } from './encryption/Encrypter.ts'

// ── Hashing ───────────────────────────────────────────────────────────────────
export { HashManager } from './hashing/HashManager.ts'
export { BcryptHasher } from './hashing/BcryptHasher.ts'
export { Argon2Hasher } from './hashing/Argon2Hasher.ts'

// ── Cache ─────────────────────────────────────────────────────────────────────
export { CacheManager } from './cache/CacheManager.ts'
export type { CacheConfig } from './cache/CacheManager.ts'
export { MemoryCacheStore } from './cache/MemoryCacheStore.ts'
export { FileCacheStore } from './cache/FileCacheStore.ts'
export { RedisCacheStore } from './cache/RedisCacheStore.ts'
export type { RedisCacheConfig } from './cache/RedisCacheStore.ts'
export { MemcachedCacheStore } from './cache/MemcachedCacheStore.ts'
export type { MemcachedCacheConfig } from './cache/MemcachedCacheStore.ts'
export { NullCacheStore } from './cache/NullCacheStore.ts'
export { CacheHit, CacheMissed, KeyWritten, KeyForgotten } from './cache/events.ts'

// ── Session ───────────────────────────────────────────────────────────────────
export { SessionManager } from './session/SessionManager.ts'
export { SessionStore } from './session/Store.ts'
export { MemorySessionHandler } from './session/handlers/MemorySessionHandler.ts'
export { FileSessionHandler } from './session/handlers/FileSessionHandler.ts'
export { CookieSessionHandler } from './session/handlers/CookieSessionHandler.ts'

// ── Global helpers ────────────────────────────────────────────────────────────
export { config } from './helpers/config.ts'
export { env } from './helpers/env.ts'
export { app } from './helpers/app.ts'
export { route, ROUTER } from './helpers/route.ts'
export { abort } from './helpers/abort.ts'
export { encrypt, decrypt, ENCRYPTER } from './helpers/encrypt.ts'
export { response, json, html, redirect, noContent, stream, download } from './helpers/response.ts'
export { hash, hashCheck } from './helpers/hash.ts'
export { cache } from './helpers/cache.ts'
export { session } from './helpers/session.ts'
