/**
 * Structured error codes for all MantiqJS framework errors.
 *
 * Each error code follows the pattern `E_{CATEGORY}_{DESCRIPTION}`.
 */
export const ErrorCodes = {
  AUTH_UNAUTHENTICATED: 'E_AUTH_UNAUTHENTICATED',
  AUTH_UNAUTHORIZED: 'E_AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'E_AUTH_FORBIDDEN',
  VALIDATION_FAILED: 'E_VALIDATION_FAILED',
  MODEL_NOT_FOUND: 'E_MODEL_NOT_FOUND',
  ROUTE_NOT_FOUND: 'E_ROUTE_NOT_FOUND',
  CSRF_MISMATCH: 'E_CSRF_MISMATCH',
  ENCRYPTION_FAILED: 'E_ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'E_DECRYPTION_FAILED',
  MISSING_APP_KEY: 'E_MISSING_APP_KEY',
  RATE_LIMITED: 'E_RATE_LIMITED',
  CONTAINER_RESOLUTION: 'E_CONTAINER_RESOLUTION',
  CONFIG_NOT_FOUND: 'E_CONFIG_NOT_FOUND',
  QUERY_ERROR: 'E_QUERY_ERROR',
  CONNECTION_LOST: 'E_CONNECTION_LOST',
  CONNECTION_FAILED: 'E_CONNECTION_FAILED',
  DRIVER_NOT_SUPPORTED: 'E_DRIVER_NOT_SUPPORTED',
  HTTP_ERROR: 'E_HTTP_ERROR',
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
