import { Format, type GeneratedFile } from './Format.ts'
import type { BuiltRules } from '../rules/RuleRegistry.ts'

/**
 * Generates a single CLAUDE.md file for Claude Code.
 */
export class ClaudeFormat extends Format {
  readonly name = 'claude'
  readonly description = 'Claude Code (CLAUDE.md)'

  generate(rules: BuiltRules): GeneratedFile[] {
    let content = `<!-- Generated by @mantiq/agent-rules. Regenerate with: bun mantiq agent:generate -->\n`
    content += `# CLAUDE.md\n\n`
    content += `This file provides guidance to Claude Code when working with this MantiqJS project.\n\n`

    for (const section of rules.sections) {
      content += `## ${section.title}\n\n`
      content += section.content
      content += '\n\n'
    }

    return [{ path: 'CLAUDE.md', content: content.trimEnd() + '\n' }]
  }
}
