import { Format, type GeneratedFile } from './Format.ts'
import type { BuiltRules } from '../rules/RuleRegistry.ts'

/**
 * Generates .github/copilot-instructions.md for GitHub Copilot.
 */
export class CopilotFormat extends Format {
  readonly name = 'copilot'
  readonly description = 'GitHub Copilot (.github/copilot-instructions.md)'

  generate(rules: BuiltRules): GeneratedFile[] {
    let content = `<!-- Generated by @mantiq/agent-rules. Regenerate with: bun mantiq agent:generate -->\n`
    content += `# MantiqJS Copilot Instructions\n\n`

    for (const section of rules.sections) {
      content += `## ${section.title}\n\n`
      content += section.content
      content += '\n\n'
    }

    return [{ path: '.github/copilot-instructions.md', content: content.trimEnd() + '\n' }]
  }
}
