import { Format, type GeneratedFile } from './Format.ts'
import type { BuiltRules } from '../rules/RuleRegistry.ts'

/**
 * Generates .windsurfrules for Windsurf IDE.
 */
export class WindsurfFormat extends Format {
  readonly name = 'windsurf'
  readonly description = 'Windsurf (.windsurfrules)'

  generate(rules: BuiltRules): GeneratedFile[] {
    let content = `# MantiqJS Windsurf Rules\n`
    content += `# Generated by @mantiq/agent-rules. Regenerate with: bun mantiq agent:generate\n\n`

    for (const section of rules.sections) {
      content += `## ${section.title}\n\n`
      content += section.content
      content += '\n\n'
    }

    return [{ path: '.windsurfrules', content: content.trimEnd() + '\n' }]
  }
}
