import { describe, test, expect } from 'bun:test'
import { Mailable } from '../../src/Mailable.ts'
import type { MailAddress } from '../../src/contracts/MailConfig.ts'

// ── Concrete mailable subclasses for testing ────────────────────────────────

class WelcomeMail extends Mailable {
  constructor(private name: string) { super() }

  override build(): void {
    this.setSubject(`Welcome, ${this.name}!`)
    this.html(`<h1>Hello ${this.name}</h1>`)
  }
}

class MarkdownMail extends Mailable {
  override build(): void {
    this.setSubject('Markdown Email')
    this.markdown('# Hello\n\nThis is a **test**.')
  }
}

class TextOnlyMail extends Mailable {
  override build(): void {
    this.setSubject('Plain Text')
    this.text('Hello plain text')
  }
}

class AttachmentMail extends Mailable {
  override build(): void {
    this.setSubject('With Attachment')
    this.html('<p>See attached</p>')
    this.attach('report.csv', 'col1,col2\nval1,val2', 'text/csv')
  }
}

class HeaderMail extends Mailable {
  override build(): void {
    this.setSubject('Custom Headers')
    this.text('body')
    this.header('X-Campaign', 'launch-2026')
  }
}

const DEFAULT_FROM: MailAddress = { address: 'noreply@example.com', name: 'App' }

describe('Mailable', () => {
  // ── Recipients ──────────────────────────────────────────────────────────────

  test('to() accepts a string', () => {
    const mail = new WelcomeMail('Alice')
    const result = mail.to('alice@example.com')

    expect(result).toBe(mail)
    expect(mail.getTo()).toEqual([{ address: 'alice@example.com' }])
  })

  test('to() accepts a MailAddress object', () => {
    const mail = new WelcomeMail('Alice')
    mail.to({ address: 'alice@example.com', name: 'Alice' })

    expect(mail.getTo()).toEqual([{ address: 'alice@example.com', name: 'Alice' }])
  })

  test('to() accepts an array of addresses', () => {
    const mail = new WelcomeMail('Alice')
    mail.to(['a@b.com', { address: 'c@d.com', name: 'Charlie' }])

    expect(mail.getTo()).toHaveLength(2)
    expect(mail.getTo()[0]).toEqual({ address: 'a@b.com' })
    expect(mail.getTo()[1]).toEqual({ address: 'c@d.com', name: 'Charlie' })
  })

  test('cc() sets cc recipients', () => {
    const mail = new WelcomeMail('Alice')
    const result = mail.cc('cc@example.com')

    expect(result).toBe(mail)
    expect(mail.getCc()).toEqual([{ address: 'cc@example.com' }])
  })

  test('cc() accepts an array', () => {
    const mail = new WelcomeMail('Alice')
    mail.cc(['a@b.com', 'c@d.com'])

    expect(mail.getCc()).toHaveLength(2)
  })

  test('bcc() sets bcc recipients', () => {
    const mail = new WelcomeMail('Alice')
    const result = mail.bcc('bcc@example.com')

    expect(result).toBe(mail)
    expect(mail.getBcc()).toEqual([{ address: 'bcc@example.com' }])
  })

  test('replyTo() sets reply-to address', () => {
    const mail = new WelcomeMail('Alice')
    const result = mail.replyTo('reply@example.com')

    expect(result).toBe(mail)
  })

  // ── build() + toMessage() ─────────────────────────────────────────────────

  test('toMessage() calls build() and returns a Message with HTML content', () => {
    const mail = new WelcomeMail('Alice')
    mail.to('alice@example.com')

    const msg = mail.toMessage(DEFAULT_FROM)

    expect(msg.from).toEqual(DEFAULT_FROM)
    expect(msg.subject).toBe('Welcome, Alice!')
    expect(msg.html).toBe('<h1>Hello Alice</h1>')
    expect(msg.to).toEqual([{ address: 'alice@example.com' }])
  })

  test('toMessage() with markdown renders HTML and generates text fallback', () => {
    const mail = new MarkdownMail()
    mail.to('user@example.com')

    const msg = mail.toMessage(DEFAULT_FROM)

    expect(msg.subject).toBe('Markdown Email')
    expect(msg.html).toContain('<h1')
    expect(msg.html).toContain('Hello')
    expect(msg.html).toContain('<strong>test</strong>')
    // text fallback is generated by stripping markdown syntax
    expect(msg.text).toBeTruthy()
    expect(msg.text).toContain('Hello')
    expect(msg.text).toContain('test')
  })

  test('toMessage() with text-only content', () => {
    const mail = new TextOnlyMail()
    const msg = mail.toMessage(DEFAULT_FROM)

    expect(msg.subject).toBe('Plain Text')
    expect(msg.text).toBe('Hello plain text')
    expect(msg.html).toBeNull()
  })

  test('toMessage() includes attachments', () => {
    const mail = new AttachmentMail()
    const msg = mail.toMessage(DEFAULT_FROM)

    expect(msg.attachments).toHaveLength(1)
    expect(msg.attachments[0]).toEqual({
      filename: 'report.csv',
      content: 'col1,col2\nval1,val2',
      contentType: 'text/csv',
    })
  })

  test('toMessage() includes custom headers', () => {
    const mail = new HeaderMail()
    const msg = mail.toMessage(DEFAULT_FROM)

    expect(msg.headers['X-Campaign']).toBe('launch-2026')
  })

  test('toMessage() transfers cc, bcc, replyTo to the message', () => {
    const mail = new WelcomeMail('Alice')
    mail.to('alice@example.com')
    mail.cc('cc@example.com')
    mail.bcc('bcc@example.com')
    mail.replyTo('reply@example.com')

    const msg = mail.toMessage(DEFAULT_FROM)

    expect(msg.cc).toEqual([{ address: 'cc@example.com' }])
    expect(msg.bcc).toEqual([{ address: 'bcc@example.com' }])
    expect(msg.replyTo).toEqual([{ address: 'reply@example.com' }])
  })

  // ── getSubject() ────────────────────────────────────────────────────────────

  test('getSubject() returns empty string before build()', () => {
    const mail = new WelcomeMail('Alice')
    expect(mail.getSubject()).toBe('')
  })

  // ── setAppName() ────────────────────────────────────────────────────────────

  test('setAppName() changes the app name used in markdown layout', () => {
    const mail = new MarkdownMail()
    mail.setAppName('MyApp')

    const msg = mail.toMessage(DEFAULT_FROM)

    // The rendered HTML should contain the custom app name in the layout
    expect(msg.html).toContain('MyApp')
  })

  // ── html() clears markdown, markdown() clears html ──────────────────────

  test('html() and markdown() are mutually exclusive', () => {
    class ToggleMail extends Mailable {
      override build(): void {
        this.setSubject('Toggle')
        this.markdown('# First')
        this.html('<p>Override</p>')
      }
    }

    const msg = new ToggleMail().toMessage(DEFAULT_FROM)

    expect(msg.html).toBe('<p>Override</p>')
    // markdown was cleared, so no layout wrapping
    expect(msg.html).not.toContain('<!DOCTYPE html>')
  })

  test('markdown() after html() clears html', () => {
    class ToggleMail2 extends Mailable {
      override build(): void {
        this.setSubject('Toggle')
        this.html('<p>First</p>')
        this.markdown('# Override')
      }
    }

    const msg = new ToggleMail2().toMessage(DEFAULT_FROM)

    // Should render as markdown layout, not raw HTML
    expect(msg.html).toContain('<!DOCTYPE html>')
    expect(msg.html).toContain('Override')
  })
})
