export default {
  title: 'Mail',
  content: `
<h2 id="introduction">Introduction</h2>
<p>The <code>@mantiq/mail</code> package provides a driver-based transactional email system. It includes message building, mailable classes, transport drivers (SMTP, Resend, SendGrid, Mailgun, Postmark, AWS SES, Log, Array), markdown-to-HTML rendering, queued sending, and testing fakes. The architecture follows the same driver pattern used throughout MantiqJS &mdash; swap or extend any transport without changing your application code.</p>

<h2 id="configuration">Configuration</h2>
<p>Mail is configured in <code>config/mail.ts</code>. This file defines the default mailer, the global &ldquo;from&rdquo; address, and all available mailers:</p>

<pre><code class="language-typescript">export default {
  default: 'smtp',

  from: {
    address: 'hello@example.com',
    name: 'My App',
  },

  mailers: {
    smtp: {
      driver: 'smtp',
      host: 'smtp.mailgun.org',
      port: 587,
      username: 'postmaster@example.com',
      password: 'secret',
      encryption: 'tls',
    },

    resend: {
      driver: 'resend',
      apiKey: 're_...',
    },

    sendgrid: {
      driver: 'sendgrid',
      apiKey: 'SG...',
    },

    mailgun: {
      driver: 'mailgun',
      apiKey: 'key-...',
      domain: 'mg.example.com',
      region: 'us',
    },

    postmark: {
      driver: 'postmark',
      serverToken: 'xxxx-xxxx-xxxx',
    },

    ses: {
      driver: 'ses',
      region: 'us-east-1',
      accessKeyId: 'AKIA...',
      secretAccessKey: '...',
    },

    log: {
      driver: 'log',
    },

    array: {
      driver: 'array',
    },
  },
}
</code></pre>

<p>If no mail configuration is provided, MantiqJS defaults to the <code>log</code> driver, which prints messages to the console &mdash; handy for local development.</p>

<h3 id="mail-config-type">MailConfig Type</h3>
<p>The configuration follows the <code>MailConfig</code> interface:</p>

<pre><code class="language-typescript">interface MailConfig {
  default: string
  from: MailAddress
  mailers: Record&lt;string, MailerConfig&gt;
}
</code></pre>

<h3 id="mail-address">MailAddress</h3>
<p>Addresses throughout the mail system use the <code>MailAddress</code> interface:</p>

<pre><code class="language-typescript">interface MailAddress {
  address: string
  name?: string
}
</code></pre>

<h2 id="registering-the-service-provider">Registering the Service Provider</h2>
<p>Register <code>MailServiceProvider</code> in your application bootstrap (<code>index.ts</code>):</p>

<pre><code class="language-typescript">import { MailServiceProvider } from '@mantiq/mail'

await app.registerProviders([CoreServiceProvider, MailServiceProvider])
await app.bootProviders()
</code></pre>

<p>The provider reads the <code>mail</code> key from <code>ConfigRepository</code> and registers <code>MailManager</code> as a singleton in the container.</p>

<h2 id="mailable-class">Mailable Class</h2>
<p>Each type of email sent by your application is represented as a <code>Mailable</code> class. These classes live in the <code>app/Mail</code> directory and have a single <code>build()</code> method where you configure the subject, content, and attachments.</p>

<h3 id="generating-mailables">Generating Mailables</h3>
<p>Use the <code>make:mail</code> command to generate a new mailable:</p>

<pre><code class="language-typescript">npx mantiq make:mail WelcomeEmail
npx mantiq make:mail OrderConfirmation --markdown
</code></pre>

<h3 id="writing-mailables">Writing Mailables</h3>
<p>Inside the <code>build()</code> method, use the protected setters to configure the message. These include <code>setSubject()</code>, <code>html()</code>, <code>text()</code>, <code>markdown()</code>, <code>attach()</code>, and <code>header()</code>:</p>

<pre><code class="language-typescript">import { Mailable } from '@mantiq/mail'

class WelcomeEmail extends Mailable {
  constructor(private userName: string) {
    super()
  }

  override build(): void {
    this.setSubject('Welcome aboard!')
        .html(\`
          &lt;h1&gt;Hello, \${this.userName}!&lt;/h1&gt;
          &lt;p&gt;Thanks for signing up.&lt;/p&gt;
        \`)
  }
}
</code></pre>

<h3 id="html-vs-markdown">HTML vs Markdown Content</h3>
<p>A mailable can use either <code>html()</code> or <code>markdown()</code> for its body, but not both simultaneously. Calling <code>html()</code> clears any previously set markdown, and calling <code>markdown()</code> clears any previously set HTML. Only one content mode is active at a time.</p>

<h3 id="plain-text-fallback">Plain Text Fallback</h3>
<p>When using <code>markdown()</code>, a plain text fallback is automatically generated by stripping markdown and HTML tags from the source content. You can override this by explicitly calling <code>text()</code> with your own plain text version.</p>

<h3 id="recipients-on-mailables">Setting Recipients on Mailables</h3>
<p>Recipients can be set directly on the mailable using the public <code>to()</code>, <code>cc()</code>, <code>bcc()</code>, and <code>replyTo()</code> methods. These accept a string, a <code>MailAddress</code> object, or an array of either:</p>

<pre><code class="language-typescript">const email = new WelcomeEmail('Alice')
email.to('alice@example.com')
email.cc([
  'admin@example.com',
  { address: 'boss@example.com', name: 'The Boss' }
])
email.bcc('archive@example.com')
email.replyTo('support@example.com')
</code></pre>

<h3 id="attachments">Attachments</h3>
<p>Use the <code>attach()</code> method inside <code>build()</code> to add files:</p>

<pre><code class="language-typescript">class InvoiceEmail extends Mailable {
  constructor(private pdfContent: Uint8Array) {
    super()
  }

  override build(): void {
    this.setSubject('Your Invoice')
        .html('&lt;p&gt;Please find your invoice attached.&lt;/p&gt;')
        .attach('invoice.pdf', this.pdfContent, 'application/pdf')
  }
}
</code></pre>

<h3 id="custom-headers">Custom Headers</h3>
<p>Add custom email headers using the <code>header()</code> method inside <code>build()</code>:</p>

<pre><code class="language-typescript">override build(): void {
  this.setSubject('Order Shipped')
      .html('&lt;p&gt;Your order has shipped!&lt;/p&gt;')
      .header('X-Order-Id', '12345')
}
</code></pre>

<h2 id="message">Message</h2>
<p>The <code>Message</code> class is a value object representing the full email envelope and body. It holds the from address, recipients, subject, HTML/text bodies, attachments, and custom headers. A <code>Mailable</code> is converted to a <code>Message</code> via its <code>toMessage(from)</code> method before being passed to a transport driver.</p>

<pre><code class="language-typescript">import { Message } from '@mantiq/mail'

const msg = new Message()
msg.setFrom({ address: 'noreply@example.com', name: 'My App' })
   .addTo('user@example.com')
   .addCc({ address: 'cc@example.com', name: 'CC Person' })
   .setSubject('Hello')
   .setHtml('&lt;h1&gt;Hello!&lt;/h1&gt;')
   .setText('Hello!')
   .addAttachment('file.txt', 'Hello world', 'text/plain')
   .setHeader('X-Custom', 'value')
</code></pre>

<p>All setters return <code>this</code> for fluent chaining. String arguments to <code>setFrom()</code>, <code>addTo()</code>, etc. are automatically wrapped as <code>{ address: str }</code>.</p>

<h3 id="formatting-addresses">Formatting Addresses</h3>
<p>The <code>Message</code> class provides static helpers for formatting addresses:</p>

<pre><code class="language-typescript">Message.formatAddress({ address: 'a@b.com', name: 'Alice' })
// =&gt; 'Alice &lt;a@b.com&gt;'

Message.formatAddress({ address: 'a@b.com' })
// =&gt; 'a@b.com'

Message.formatAddresses([
  { address: 'a@b.com', name: 'Alice' },
  { address: 'b@b.com' }
])
// =&gt; 'Alice &lt;a@b.com&gt;, b@b.com'
</code></pre>

<h2 id="transports">Transport Drivers</h2>
<p>All transport drivers implement the <code>MailTransport</code> interface, which has a single method:</p>

<pre><code class="language-typescript">interface MailTransport {
  send(message: Message): Promise&lt;{ id: string }&gt;
}
</code></pre>

<p>The returned <code>id</code> is a provider-specific message identifier.</p>

<h3 id="smtp-transport">SMTP</h3>
<p>Sends email via raw SMTP using Bun TCP sockets (<code>Bun.connect</code>). Supports TLS, STARTTLS, and plaintext connections, with AUTH PLAIN and AUTH LOGIN authentication.</p>

<pre><code class="language-typescript">mailers: {
  smtp: {
    driver: 'smtp',
    host: 'smtp.example.com',
    port: 587,
    username: 'user@example.com',
    password: 'secret',
    encryption: 'tls',  // 'tls' | 'starttls' | 'none'
  },
}
</code></pre>

<p>The SMTP transport handles the full RFC 2822 conversation: greeting, EHLO, optional STARTTLS upgrade, authentication, envelope (MAIL FROM / RCPT TO), DATA with MIME message building (multipart/mixed for attachments, multipart/alternative for HTML + text), and QUIT.</p>

<h3 id="ses-transport">AWS SES</h3>
<p>Sends via the AWS SES v2 API with full Signature V4 signing using <code>crypto.subtle</code>:</p>

<pre><code class="language-typescript">mailers: {
  ses: {
    driver: 'ses',
    region: 'us-east-1',
    accessKeyId: 'AKIA...',
    secretAccessKey: '...',
  },
}
</code></pre>

<h3 id="sendgrid-transport">SendGrid</h3>
<p>Sends via the SendGrid v3 API:</p>

<pre><code class="language-typescript">mailers: {
  sendgrid: {
    driver: 'sendgrid',
    apiKey: 'SG...',
  },
}
</code></pre>

<h3 id="mailgun-transport">Mailgun</h3>
<p>Sends via the Mailgun API using multipart <code>FormData</code>. Supports both US and EU regions:</p>

<pre><code class="language-typescript">mailers: {
  mailgun: {
    driver: 'mailgun',
    apiKey: 'key-...',
    domain: 'mg.example.com',
    region: 'us',  // 'us' | 'eu'
  },
}
</code></pre>

<p>The base URL varies by region: <code>https://api.mailgun.net</code> for US, <code>https://api.eu.mailgun.net</code> for EU.</p>

<h3 id="postmark-transport">Postmark</h3>
<p>Sends via the Postmark API:</p>

<pre><code class="language-typescript">mailers: {
  postmark: {
    driver: 'postmark',
    serverToken: 'xxxx-xxxx-xxxx',
  },
}
</code></pre>

<h3 id="resend-transport">Resend</h3>
<p>Sends via the Resend HTTP API:</p>

<pre><code class="language-typescript">mailers: {
  resend: {
    driver: 'resend',
    apiKey: 're_...',
  },
}
</code></pre>

<h3 id="log-transport">Log</h3>
<p>Logs a summary of each message to <code>console.log</code> instead of sending it. The output includes the To address, subject, and a 200-character preview. Ideal for local development:</p>

<pre><code class="language-typescript">mailers: {
  log: {
    driver: 'log',
  },
}
</code></pre>

<h3 id="array-transport">Array</h3>
<p>Stores all sent messages in an in-memory array. Useful for testing:</p>

<pre><code class="language-typescript">import { ArrayTransport } from '@mantiq/mail'

const transport = new ArrayTransport()
await transport.send(message)

console.log(transport.sent)  // Message[]
transport.flush()             // Clear all stored messages
</code></pre>

<h2 id="mail-manager">MailManager</h2>
<p>The <code>MailManager</code> is the central class for sending email. It manages driver resolution, caching, and provides convenience methods for sending mailables.</p>

<h3 id="resolving-drivers">Resolving Drivers</h3>
<p>Use <code>driver()</code> or its alias <code>mailer()</code> to get a transport instance. Drivers are lazily resolved and cached:</p>

<pre><code class="language-typescript">import { mail } from '@mantiq/mail'

// Get the default transport
const transport = mail().driver()

// Get a specific transport by name
const resendTransport = mail().driver('resend')

// mailer() is an alias for driver()
const smtpTransport = mail().mailer('smtp')
</code></pre>

<h3 id="sending-mail">Sending Mail</h3>
<p>Send a mailable directly through the manager:</p>

<pre><code class="language-typescript">import { mail } from '@mantiq/mail'

await mail().send(new WelcomeEmail('Alice'))
</code></pre>

<h3 id="extending-with-custom-drivers">Extending with Custom Drivers</h3>
<p>Register a custom transport driver using <code>extend()</code>:</p>

<pre><code class="language-typescript">import { mail } from '@mantiq/mail'
import type { MailTransport, Message } from '@mantiq/mail'

class WebhookTransport implements MailTransport {
  async send(message: Message): Promise&lt;{ id: string }&gt; {
    const response = await fetch('https://hooks.example.com/email', {
      method: 'POST',
      body: JSON.stringify({ subject: message.subject, html: message.html }),
    })
    const data = await response.json()
    return { id: data.id }
  }
}

mail().extend('webhook', () =&gt; new WebhookTransport())

// Now you can use it
const transport = mail().driver('webhook')
</code></pre>

<p>Calling <code>extend()</code> clears any cached instance for that driver name, so the next call to <code>driver()</code> will use the new factory.</p>

<h2 id="pending-mail">PendingMail</h2>
<p><code>PendingMail</code> provides a fluent API for building and sending emails. You get a <code>PendingMail</code> instance by calling <code>mail().to()</code> or <code>mail('user@example.com')</code>:</p>

<pre><code class="language-typescript">import { mail } from '@mantiq/mail'

await mail().to('alice@example.com')
  .cc('bob@example.com')
  .bcc('archive@example.com')
  .send(new WelcomeEmail('Alice'))
</code></pre>

<h3 id="specifying-the-mailer">Specifying the Mailer</h3>
<p>Use <code>via()</code> to send through a specific mailer instead of the default:</p>

<pre><code class="language-typescript">await mail().to('alice@example.com')
  .via('resend')
  .send(new WelcomeEmail('Alice'))
</code></pre>

<h3 id="recipient-merging">Recipient Merging</h3>
<p>Recipients set on the <code>PendingMail</code> are merged with any recipients already configured on the mailable in its <code>build()</code> method.</p>

<h2 id="markdown-emails">Markdown Emails</h2>
<p>Mailables can use the <code>markdown()</code> content method to write email bodies using a simplified markdown syntax. The content is automatically rendered into a fully styled, responsive HTML email template.</p>

<pre><code class="language-typescript">import { Mailable } from '@mantiq/mail'

class OrderShippedEmail extends Mailable {
  constructor(
    private orderId: string,
    private trackingUrl: string,
  ) {
    super()
  }

  override build(): void {
    this.setSubject('Your Order Has Shipped!')
        .markdown(\`
# Order Shipped

Your order **#\${this.orderId}** has been shipped and is on its way!

[button url="\${this.trackingUrl}"]Track Your Order[/button]

[panel]
If you have any questions about your order, reply to this email
or contact our support team.
[/panel]

Thanks for shopping with us!
        \`)
  }
}
</code></pre>

<h3 id="supported-markdown-syntax">Supported Syntax</h3>
<p>The markdown renderer supports the following syntax:</p>
<ul>
  <li>Headings (<code># h1</code> through <code>###### h6</code>)</li>
  <li>Paragraphs (plain text lines)</li>
  <li>Bold (<code>**text**</code>) and italic (<code>*text*</code>)</li>
  <li>Links (<code>[text](url)</code>)</li>
  <li>Inline code (<code>\`code\`</code>)</li>
  <li>Blockquotes (<code>&gt; text</code>)</li>
  <li>Unordered lists (<code>- item</code>, <code>* item</code>, <code>+ item</code>)</li>
  <li>Ordered lists (<code>1. item</code>)</li>
  <li>Horizontal rules (<code>---</code>, <code>***</code>, <code>___</code>)</li>
  <li>Button component: <code>[button url="..."]Click me[/button]</code></li>
  <li>Panel component (multi-line): <code>[panel]...[/panel]</code></li>
</ul>

<h3 id="markdown-theme">Theme and Layout</h3>
<p>The rendered HTML is wrapped in a responsive email layout with:</p>
<ul>
  <li>600px max-width centered table layout (email-client safe)</li>
  <li>Inline CSS (email clients strip <code>&lt;style&gt;</code> tags)</li>
  <li>Dark mode support via <code>@media (prefers-color-scheme: dark)</code></li>
  <li>Header with app name and footer with copyright year</li>
  <li>Mobile responsive via <code>@media (max-width: 620px)</code></li>
</ul>

<h3 id="markdown-components">Components</h3>
<p>The theme module exports individual components you can use directly:</p>

<pre><code class="language-typescript">import { renderButton, renderPanel, renderTable, wrapInLayout } from '@mantiq/mail'

const buttonHtml = renderButton('https://example.com', 'Click Me')
const panelHtml = renderPanel('Important notice content here.')
const tableHtml = renderTable(['Name', 'Email'], [
  ['Alice', 'alice@example.com'],
  ['Bob', 'bob@example.com'],
])
const fullEmail = wrapInLayout(bodyHtml, { appName: 'My App' })
</code></pre>

<h2 id="queueing-mail">Queueing Mail</h2>
<p>If you have <code>@mantiq/queue</code> installed, you can queue mailables for asynchronous sending using <code>queue()</code> instead of <code>send()</code>:</p>

<pre><code class="language-typescript">await mail().to('alice@example.com')
  .queue(new WelcomeEmail('Alice'))
</code></pre>

<p>This dispatches a <code>SendMailJob</code> that retries up to 3 times on failure. If <code>@mantiq/queue</code> is not installed, <code>queue()</code> falls back to synchronous sending automatically.</p>

<p><code>@mantiq/queue</code> is an optional peer dependency. Queueing works seamlessly when installed and degrades gracefully to synchronous sending when it is not.</p>

<h2 id="helpers">Helpers</h2>
<p>The <code>mail()</code> helper function is the primary way to interact with the mail system. It is overloaded for convenience:</p>

<pre><code class="language-typescript">import { mail } from '@mantiq/mail'

// Without arguments: returns the MailManager instance
const manager = mail()

// With a 'to' string: returns a PendingMail ready for chaining
await mail('alice@example.com').send(new WelcomeEmail('Alice'))
</code></pre>

<p>The helper resolves the <code>MailManager</code> singleton from the IoC container using the <code>MAIL_MANAGER</code> symbol.</p>

<h2 id="testing">Testing with MailFake</h2>
<p>The <code>MailFake</code> class implements the <code>MailTransport</code> interface and provides assertion methods for verifying that mailables were sent or queued during tests.</p>

<pre><code class="language-typescript">import { MailFake } from '@mantiq/mail'

const fake = new MailFake()

// Record sent and queued mailables
fake.recordSent(new WelcomeEmail('Alice'))
fake.recordQueued(new OrderConfirmation('123'))
</code></pre>

<h3 id="available-assertions">Available Assertions</h3>

<pre><code class="language-typescript">// Assert a mailable class was sent
fake.assertSent(WelcomeEmail)

// Assert a mailable was sent exactly N times
fake.assertSent(WelcomeEmail, 2)

// Assert a mailable was NOT sent
fake.assertNotSent(InvoiceEmail)

// Assert a mailable was queued
fake.assertQueued(OrderConfirmation)

// Assert a mailable was queued exactly N times
fake.assertQueued(OrderConfirmation, 1)

// Assert nothing was sent or queued
fake.assertNothingSent()
fake.assertNothingQueued()
</code></pre>

<h3 id="inspecting-sent-mail">Inspecting Sent Mail</h3>
<p>Access the raw recorded data for custom assertions:</p>

<pre><code class="language-typescript">// Get raw Message objects recorded via send()
const messages = fake.sent()

// Get Mailable instances recorded via recordSent()
const mailables = fake.sentMailables()

// Get Mailable instances recorded via recordQueued()
const queued = fake.queued()

// Clear all recorded data
fake.reset()
</code></pre>

<h2 id="errors">Errors</h2>
<p>All mail errors throw <code>MailError</code>, which extends <code>MantiqError</code>. This includes API errors from transport providers, SMTP protocol failures, and configuration issues. The optional <code>context</code> record carries driver-specific details such as HTTP status codes, response bodies, and available driver names:</p>

<pre><code class="language-typescript">import { MailError } from '@mantiq/mail'

try {
  await mail().send(new WelcomeEmail('Alice'))
} catch (error) {
  if (error instanceof MailError) {
    console.error(error.message, error.context)
  }
}
</code></pre>
`
}
